/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_BACK.h"
#include "ADC_SAR_1.h"
#include "IN_B2_aliases.h"
#include "IN_B2.h"
#include "ADC1_input_aliases.h"
#include "ADC1_input.h"
#include "Clock_1.h"
#include "IN_A2_aliases.h"
#include "IN_A2.h"
#include "PWM2_output_1_aliases.h"
#include "PWM2_output_1.h"
#include "PWM1_output_1_aliases.h"
#include "PWM1_output_1.h"
#include "IN_A1_aliases.h"
#include "IN_A1.h"
#include "IN_B1_aliases.h"
#include "IN_B1.h"
#include "PWM_FRONT.h"
#include "UART_1.h"
#include "PWM2_output_2_aliases.h"
#include "PWM2_output_2.h"
#include "PWM1_output_2_aliases.h"
#include "PWM1_output_2.h"
#include "IN_A2_1_aliases.h"
#include "IN_A2_1.h"
#include "IN_B2_1_aliases.h"
#include "IN_B2_1.h"
#include "IN_A1_1_aliases.h"
#include "IN_A1_1.h"
#include "IN_B1_1_aliases.h"
#include "IN_B1_1.h"
#include "inter_uart.h"
#include "Clock_2.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_1_Bypass_aliases.h"
#include "ADC_SAR_1_Bypass.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

